[phases.setup]
aptPkgs = [
    "libgl1", 
    "libglib2.0-0", 
    "libxcb1", 
    "libxext6"
]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "pip uninstall -y opencv-python",
    "pip install opencv-python-headless==4.13.0.92"
]